spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://194.163.133.60:5432/blogging
    username: postgres
    password: 1309
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  messages:
    always-use-message-format: true
